### ISSUE TITLE
Pyroscope SSL Enabling

### ISSUE THREAD

**Issue by vikasmav** [grafana/pyroscope#3596] opened 2024-09-27 16:50 UTC
Need an input , I am trying to deploy Pyroscope in one of my linux node but want https to be enabled.  I have placed certifcates in my server configuration and querier frontend , querier scheduler etc have been configured
with tls-enabled as true and tls insecure as true too.

But when I access the pyroscope admin page with https the initial load is happening with errors.
The apps in the dropdown are net getting displayed with the error being displayed as EOF Exception.

How to resolve it?

[9:32](https://pyroscope.slack.com/archives/D07Q2UFSFQQ/p1727452952981849)
Please find the config
#### Environment

- LINUX NODE

[PYRO_CONFIG.txt](https://github.com/user-attachments/files/17167270/PYRO_CONFIG.txt)

**Comment by kolesnikovae** [comment] 2024-09-30 04:21
Duplicate of https://github.com/grafana/pyroscope/issues/3598

**Closed by kolesnikovae** 2024-09-30 04:21 UTC
