### ISSUE TITLE
Pyroscope Login and SSL related

### ISSUE THREAD

**Issue by vikasmav** [grafana/pyroscope#3597] opened 2024-09-27 16:59 UTC
I am deploying Pyroscope in Micro Service Mode in Kubernetes, below are my concerns

1) Does Pyroscope has login screen which can be either integrated with LDAP or atleast create few users with some credentials
    and those users can login with  the provided creds.

2) When deployed in Kubernetes Microservice mode, how to enable tls is unclear.
    There is no documentation related to that or even when it is deployed in monolith mode.
   I believe we can update the documentation with those details.

Can anyone please answer the above?

Thank you 
Vikas

**Comment by kolesnikovae** [comment] 2024-09-30 04:21
Duplicate of https://github.com/grafana/pyroscope/issues/3598

**Closed by kolesnikovae** 2024-09-30 04:21 UTC
