### ISSUE TITLE
Document supported hardware architectures

### ISSUE THREAD

**Issue by zamazan4ik** [grafana/pyroscope#1680] opened 2022-11-04 22:57 UTC
Hi!

Could you please put the information about supported architectures to the documentation please? E.e. about supported architectures for different operating systems, some specific requirements to the supported instructions, if you have any (e.g. maybe AVX is required - I do not know). This kind of information is important for the end-users.

I have checked the documentation and the corresponding Download pages (as a tip suggests) but no information regarding supported architectures is available there.

Thanks in advance!

**Comment by knylander-grafana** [comment] 2023-11-20 19:11
Duplicate of https://github.com/grafana/pyroscope/issues/2086

**Closed by knylander-grafana** 2023-11-20 19:11 UTC
